### ISSUE TITLE
Support auto line break and page break

### ISSUE THREAD

**Issue by xu-cheng** [gpoore/minted#1]
With auto break, minted would be perfect.

**Comment by gpoore** [comment]
Basic automatic line breaking support is now complete, so I am closing this. Automatic breaks now cooperate with `fancyvrb`'s frame option. It is now possible to put line continuation symbols in both the left and right margins. The `breakbytoken` option provides better control of where breaks occur.

I'm currently finalizing the 2.0 release. Future releases will likely bring enhancements to line breaking.

**Comment by unidesign** [comment]
I'm sorry for pushing this thread, but since automatic page break is one of the most needed things I'd really like to see an (at least) workaround to enable `mdframed` by option.

I saw that you mentioned
`
\BeforeBeginEnvironment{minted}{\begin{mdframed}}
\AfterEndEnvironment{minted}{\end{mdframed}}
`
would help to automate the process of pagebreaking and I even found out that
`
\begin{mdframed}[leftmargin=0pt,innerleftmargin=3pt,innertopmargin=3pt,rightmargin=0pt,innerrightmargin=3pt,innerbottommargin=3pt,topline=false, bottomline=false, leftline=false, rightline=false, backgroundcolor=XXX]`
will be visually the same as standard `minted` AND enable flawless pagebreaking, but I noticed it will come to an endless loop if you want to set background color using `mdframed` and `minted` together.
So the solution is to only set the background color in `mdframed` option as I made where `XXX` is the color, but I wanted to know how the color name could be passed automatically to `mdframed` from `minted`.

To be more clear, I want to have something like:
`\BeforeBeginEnvironment{minted}{\begin{mdframed}[...,backgroundcolor=#1]}`

If you have an answer for this I would be really glad, and also if you could maybe integrate it at least with in option like `breakpages`.
That would be a huge step for `minted`.

**Comment by gpoore** [comment]
@unidesign In the future, it might be better to open a new issue for something like this, since this seems to be more of a feature request or question about `mdframed` compatibility, rather than a direct continuation of the existing (closed) issue.

I think you can get most of what you want using something like the following example.  This doesn't tie everything directly into `minted`, but the typing required is about the same.  I am interested in adding integration with framing packages in the future, but since there are several popular packages (`framed`, `mdframed`, `tcolorbox`, etc.), anything that I add will be very general, something along the lines of, say, `\begin{minted}[mdfsetup={...}]{<lang>}`.

```latex
\documentclass{article}

\usepackage{xcolor}
\usepackage{mdframed}
\usepackage{minted}


\BeforeBeginEnvironment{minted}{%
  \begin{mdframed}[leftmargin=0pt,innerleftmargin=3pt,innertopmargin=3pt,
    rightmargin=0pt,innerrightmargin=3pt,innerbottommargin=3pt,topline=false,
    bottomline=false, leftline=false, rightline=false]}
\AfterEndEnvironment{minted}{\end{mdframed}}

\begin{document}

\mdfsetup{backgroundcolor=green}
\begin{minted}{python}
def f(x):
    return x**2
\end{minted}

\mdfsetup{backgroundcolor=yellow}
\begin{minted}{python}
def f(x):
    return x**2
\end{minted}

\end{document}
```

**Comment by unidesign** [comment]
@gpoore Thank you very much, this works good for me, especially because I only want one background color in general so I can set up the whole block in preamble.
I noticed no disadvantages when using `mdframed` with `minted` (except that you can not pass color every time without extra command).

PS: I also thought about creating a new topic but googling this yields to this page and also the point about page breaking wasn't answered here.
If you edit the documentation next time maybe you could add this small workaround for pagebreaking I googled more than two hours but there was not one good solution. Also the code on `stackexchange` doesn't work with color and won't give visually the same result as `minted`.
