### ISSUE TITLE
Output not what is expected when using \inputminted inside of float

### ISSUE THREAD

**Issue by jomu9721** [gpoore/minted#104]
When I try to input a file inside of a float, I do not get the expected output.  When using the following:

\begin{listing}
  \inputminted[linenos,breaklines]{python}{filename}
\end{listing}

instead of getting the listing broken up between pages, it is forcing everything on to one page, even though it doesn't fit.  It runs through the bottom margin, and off the page.

If I manually input the code into a /begin{minted} block, it works just fine.  What settings would I use to fix this behavior?

Thanks,
Josh

**Comment by gpoore** [comment]
There's a small note about this in the FAQ in the docs. The problem is that `listing` is a float, and floats can't break across pages. Instead, you can define a `longlisting` environment that will break across pages. However, this will not actually be a float, so the behavior will be a little different and may need some customization, depending on what you are doing.
```latex
\usepackage[newfloat]{minted}
\usepackage{caption}
\newenvironment{longlisting}{\captionsetup{type=listing}}{}

...

\begin{longlisting}
\inputminted[linenos,breaklines]{python}{filename}
\end{longlisting}
```
