### ISSUE TITLE
enhancement request, option to use cached file only

### ISSUE THREAD

**Issue by davidcarlisle** [gpoore/minted#113]
A request on stackexchange

http://tex.stackexchange.com/questions/280590/work-around-for-minted-code-highlighting-in-arxiv/280685#280685

asked how to use minted in a submission to arXiv (which does not allow shell escape)

what would be nice would be an option that disabled the call to pygmentize but used the cache directory if it is there, then having run minted locally you would just change the option and package the main file along with the minted generated directory without needing to cal pygmentize again. (of course it would be users responsibility to check that the cache was still valid)

**Comment by gpoore** [comment]
That's a good idea, and shouldn't be too difficult to implement. I'm currently spending all my spare time on what will become the next PythonTeX, but will try to make time soon to switch back to `minted` and work on this and the shell-escape issue.

**Comment by gpoore** [comment]
There are now new package options `finalizecache` and `frozencache`.  These allow the cache to be prepared for (`finalizecache`) and then used (`frozencache`) in an environment in which `-shell-escape`, Python, and/or Pygments are not available.  The document must be compiled with `finalizecache` first, to prepare the cache (mostly renames cache files to `listing<number>.pygtex` form, so that hashing isn't needed). Then `finalizecache` may be replaced with `frozencache`, and from that point on, `-shell-escape`, Python, and Pygments are optional.

Of course, this only works if `minted` content does not need to be modified, and if no settings that depend on Pygments or Python need to be changed. The potential pitfall is that invalid modifications can't be detected, but a procedure for checking for this is outlined in the docs.

**Comment by davidcarlisle** [comment]
Ooh thanks, should be useful I think.

**Comment by veronica320** [comment]
Tip for Overleaf users (originally from [this stackexchange post](https://tex.stackexchange.com/questions/280590/work-around-for-minted-code-highlighting-in-arxiv/280685#280685), `rhombidodecahedron'`s comment): 
> I am an Overleaf user and this worked for me, even using tcolorbox. Step one: compile with \usepackage[finalizecache,cachedir=.]{minted}. Step two: go to logs and output files > other logs and files and download everything with pyg. Step three: change finalizecache to frozencache and upload the tex+all those pyg files to arXiv. Success!
