### ISSUE TITLE
bgcolor option prevents page break

### ISSUE THREAD

**Issue by johhorn** [gpoore/minted#121]
The bgcolor option seems to prevent page break. With the following code, external files are listed fine and on different pages when bgcolor is not set. If I add bcolor=bg (or any other color, for that matter), the page breaks stop working

Setup:
```
\usepackage{minted}
\usemintedstyle{trac}
\definecolor{bg}{rgb}{0.95,0.95,0.95}
\newmintedfile[perlcode]{perl}{bgcolor=bg, breaklines, linenos=true, numberblanklines=true, showspaces=false, fontsize=\footnotesize, tabsize=2, samepage=false}
```
Usage in document:
```
\perlcode{expandSNPs.pl}
```

I use Python 2.7.10, Pigments 8.1.2, and have the latest minted.sty file in the same directory as the latex file I compile. According to TeX Live Utility, all the latex packages installed are the latest version.

Do you have any suggestions to how I can fix this? 

Without bgcolor option:
<img width="545" alt="skjermbilde 2016-05-16 kl 14 06 13" src="https://cloud.githubusercontent.com/assets/5270285/15289012/8053cd5a-1b6f-11e6-8ba2-632f2409558b.png">
With bgcolor option:
<img width="548" alt="skjermbilde 2016-05-16 kl 14 04 38" src="https://cloud.githubusercontent.com/assets/5270285/15289015/87748f34-1b6f-11e6-9249-a0d8785bd55c.png">

**Comment by gpoore** [comment]
The built-in `bgcolor` has several limitations. The solution is to use a proper framing package like `mdframed` or `tcolorbox`. There is additional information about using `mdframed` in the documentation, under `bgcolor`. `tcolorbox` also provides special `minted`-specific environments.

**Comment by Spudd86** [comment]
What's wrong with how `verbments` does it, can't you copy the method they use?

**Comment by gpoore** [comment]
@Spudd86 `verbments` is just using the `snugshade` environment from the `framed` package. You could adapt the `mdframed` example from the documentation under `bgcolor` to use `snugshade` instead.

At this point, `bgcolor` is mainly around for backwards compatibility. `mdframed` and `tcolorbox` are much more powerful, although they can sometimes require more initial configuration. I suppose it might be worth looking into switching over to `snugshade` or something similar, as long as the output is almost identical to the current `bgcolor`. And it might be worth adding in some sensible defaults for working with other framing packages. I'll try to consider that eventually, but given where everything else stands with `minted`, this doesn't have a very high priority.

**Comment by Spudd86** [comment]
Is there a workaround to get a background color in `\mintedinline` (preferably something that works with `\newmintedinline`) that also lets it break lines?

Also having a bgcolor set seems to end up making the box around the inline bigger so there's extra spacing around it so if you write `\mintedinline{c}|malloc()`'s` there's an extra bit of space between the brace and the 's if there's a bgcolor set. Is there a way to work around that too?

**Comment by gpoore** [comment]
@Spudd86 For `\mintinline`, there isn't a way to get both background color and line breaks. The standard way to get a background color is `\colorbox`, but it doesn't allow for line breaks. I tried working with `tikz` to get a version that would break, but never could get it to work properly (and the `tikz` approach always required 2 compiles). I have some horribly hackish ideas about using `\colorbox` multiple times, or even once per character, but I've never gotten back to that (although it's probably more doable now that `breakafter` and related options exist).

For the spacing issue, I believe this is due to `\fboxsep` ([example](http://tex.stackexchange.com/a/74469/10742)).

**Comment by gpoore** [comment]
I looked into @Spudd86's suggestion about the `verbments` approach, and it turned out that the `framed` package's `snugshade*` environment works very well as a replacement for the old approach. So `bgcolor` now uses `snugshade*`, which means that it supports page breaks and also resolves existing [spacing](http://tex.stackexchange.com/questions/228058/how-to-space-before-and-after-a-minted-code-block-with-bgcolor) and [margin](http://tex.stackexchange.com/questions/9097/background-colour-with-minted-package-code-misplaced) issues.

Note that the `snugshade*` approach isn't perfect. If it is used with `breaklines`, and the last line on a page is broken, in some cases the line can extend beyond the colored background. So it is still safest to use `mdframed` or `tcolorbox`. But for when you just need a background color in simple scenarios, the new approach should be a major improvement.
