### ISSUE TITLE
\mintinline in minted using escape characters does not work

### ISSUE THREAD

**Issue by auxsvr** [gpoore/minted#122]
I'm trying to use minted with a bash script with quoted awk code. The following:

\begin{minted}[escapeinside=\%\%]{awk}
 %\mintinline{bash}|awk |% ($19 =="status=404")\
 {a[gensub(/^host=/,"","g",$13) gensub(/^path="(.+)"$/,"\1","g",$12)]++;}
\end{minted}

returns the error message:

LaTeX Error: Something's wrong--perhaps a missing \item.

Is it possible to nest minted?

**Comment by gpoore** [comment]
Nesting `minted` commands/environments doesn't work, because ultimately it amounts to nesting verbatim content. For this particular case, you might consider just using `awk`. If you do want the equivalent of nesting `minted` commands/environments, it can be done with `\savebox`:
```latex
\newsavebox{\tmpbox}
\begin{lrbox}{\tmpbox}
\mintinline{bash}|awk |
\end{lrbox}

\begin{minted}[escapeinside=\%\%]{awk}
%\usebox{\tmpbox}% ($19 =="status=404")\
{a[gensub(/^host=/,"","g",$13) gensub(/^path="(.+)"$/,"\1","g",$12)]++;}
\end{minted}
```
At least with the default style, this seems to give the same result as just using `awk` for everything, without the `escapeinside`.

**Comment by auxsvr** [comment]
I resorted to using `mintinline` and switching between `bash` and `awk`. Is it possible to automate this in some way?

**Comment by gpoore** [comment]
If everything you are working with is like your example (almost all `awk`), then it might be possible to automate from the LaTeX side, especially if everything non-`awk` is right at the beginning. But if you're working with general `bash` scripts containing `awk`, then automation would probably mean writing some code that takes the script, puts it inside `\begin{minted}{awk}...\end{minted}`, and then identifies the `bash` parts and escapes them using savebox or another mechanism.

The ideal solution would be a Pygments `bash` lexer that can internally transition to `awk` at the appropriate points, but as far as I can tell, that doesn't currently exist.
