### ISSUE TITLE
Highlight lines in code snipped

### ISSUE THREAD

**Issue by dluksza** [gpoore/minted#124]
It would be great if minted can highlight particular lines in code snippets. This way it would be easer for the reader to find particular lines in listing that are referenced from text by line numbers.

**Comment by gpoore** [comment]
I'll look into adding this to my new [`fvextra` package](https://github.com/gpoore/fvextra).

**Comment by gpoore** [comment]
This is added in [v2.3](https://github.com/gpoore/minted/releases/tag/v2.3). There is a `highlightlines` option that highlights a single line or range of lines. It takes values like `{1, 3-4}`. There is also a  `highlightcolor` option. Currently, this puts a `\colorbox` behind the text, with no border padding so that it doesn't affect indentation or inter-line spacing.

**Comment by dluksza** [comment]
wow, that's awesome! thank you
