### ISSUE TITLE
'numberblanklines' option seems broken

### ISSUE THREAD

**Issue by kosmoz** [gpoore/minted#135]
In version 2.4, when using the 'numberblanklines' option, I receive the following error:
```
/home/.../main.tex:46: Package xkeyval Error: `numberblanklines' undefined in families `minted@opt@g'. [}]
```

For reference, here is my full list of options:
```
\setminted{
	frame=lines,
	breaklines=true,
	breakafter=-/,
	linenos=true,
	numberblanklines=false,
	style=manni,
	fontsize=\small,
	tabsize=4
}
```

Was it removed on purpose? If so, it should be mentioned in the changelog and removed from the documentation.

**Comment by gpoore** [comment]
It should be fixed in the last commit. This somehow got lost in the new option system that came with v2.0.

**Comment by kosmoz** [comment]
Awesome, thanks!
Will the fix, by any chance, be available via CTAN anytime soon?

**Comment by gpoore** [comment]
I can try to release a new version soon, since there are now a few fixes since the last version. However, by the time I release a new version, upload to CTAN, and CTAN updates and synchronizes, it will probably be at least a week. In the meantime, you can just download the new `minted.sty` file and put it in the directory with your document.

**Comment by kosmoz** [comment]
Okay, done and it works. Thanks again for being super responsive!
