### ISSUE TITLE
NASM highlighting parsing fails when used with disassembly listing

### ISSUE THREAD

**Issue by halsten** [gpoore/minted#152]
I am using the NASM syntax highlighting mode for minted. However, when I have disassembly listing which contains memory address numbers or with section names as well. I believe something wrong happens with the parsing and red boxes appears around those numbers as well as no syntax highlighting occurs. Here is an example:

.text:003313EB start           proc near
.text:003313EB
.text:003313EB
.text:003313EB                 call    sub_331780
.text:003313EB
.text:003313F0                 jmp     loc_33127C
.text:003313F0
.text:003313F0 start           endp

In the previous example, the red boxes will appear around the numbers `003313` with no highlight color and with white background overriding any previous settings for the minted box.

Also, there is another problem when a keyword is followed with an _ it partially highlights the keyword leaving the whole word not fully highlighted with 1 color. Here is an example:

loc_33127C:                              ; CODE XREF: start+5j
                 push    14h
                 push    offset dword_34CF70

In the previous example, the word `dword` is a reserved keyword in assembly, however the word as a whole `dword_34CF70` is a variable and should be colored with one color and not 2 colors.

--halsten

**Comment by gpoore** [comment]
This is due to [Pygments](http://pygments.org/), which `minted` uses internally for doing the highlighting. My guess would be that the NASM lexer is incomplete or has a bug. You might open an issue at the [Pygments BitBucket page](https://bitbucket.org/birkenfeld/pygments-main), or take a look at the lexer and see if you can find the problem.

In the short term, you could try [a hack to disable the red boxes](http://tex.stackexchange.com/questions/343494/minted-red-box-around-greek-characters).
