### ISSUE TITLE
Commit v2.2.2 not compatible with babel magyar

### ISSUE THREAD

**Issue by cemiarni** [gpoore/minted#158]
This removed line:  https://github.com/gpoore/minted/commit/0a8640dddff47ae31a7a0d6e3cf030c82c111907#diff-c5deba3f6233bbe803f35ede7271d9b7L557
made minted no more compatible with babel magyar package.

At build time produces `! Missing number, treated as zero.` error message.

You can reproduce with this code:
```latex
\documentclass{article}

\usepackage[magyar]{babel}
\usepackage{minted}

\begin{document}
\begin{minted}{c}
-
\end{minted}
\end{document}
```

**Comment by gpoore** [comment]
For now, you can add the following code to the preamble to get this to work with the latest `minted`:
```latex
\makeatletter
\minted@checkstyle{}
\makeatother
```
I will try to find a proper fix for this for a future version.

**Comment by xyproto** [comment]
Just to be clear: does the above mean to add this:

```
\makeatletter
\minted@checkstyle{}
\makeatother
```

to `minted.ins`, right before the `\endpreamble` line?

**Comment by gpoore** [comment]
You would want to add it in the document itself, somewhere before `\begin{document}`.

**Comment by xyproto** [comment]
I maintain the minted package for Arch Linux. Which file is the document itself?

**Comment by gpoore** [comment]
What I meant is that in any individual LaTeX document that needs to use `minted` with `magyar`, you can add that code in that specific document before the `\begin{document}`.

The code cannot just be put into the existing `minted` source code, because in general it will produce bugs. Also, even with that code, I expect that `magyar` will break `minted` when some `minted` options are used (probably anything related to changing highlight style).

**Comment by xyproto** [comment]
I see. Will just await the next release of minted and not make any changes to the minted package, then.

Thanks!

**Comment by gpoore** [comment]
The example document works now, so this should be fixed. The next `minted` release that includes this will be out in the next day or so.
