### ISSUE TITLE
`h' float specifier changed to `ht'. warnings

### ISSUE THREAD

**Issue by D4Muck** [gpoore/minted#165]
Is it intentional that you use the `h` floating specifier for the minted commands?
Because it generates `'h' float specifier changed to 'ht'.` warnings in nearly every document.

**Comment by davidcarlisle** [comment]
That is a general latex feature rather than minted, h on its own as  [h] is
almost always in error, in latex 2.09 it almost always forced all floats to
the end of the document, in latex2e we changed it to give a warning and
change to ht to give the system a chance to place it. [htp] is usually a
better option.

[h] means not top, not bottom and not on a float page so if the listing is
say 70% of the text height then unless it happens to fall in the top 30% of
the page it can not go "here" but `[h]` specifies that it can not be
deferred to the top of the next page either, so the document is infeasible,
so latex changes it to ht with a warning.

But the same is true of figures and tables not just listings.

**Comment by D4Muck** [comment]
Yeah, I know that.
The thing is, the minted package defines a `listing` environment which uses `h` as the default placement specifier.
Unless I override it with `ht` on EVERY usage it consequently produces this warning some place.

So would it be possible to change the default placement to `ht` instead of `h`?
It is defined in: https://github.com/gpoore/minted/blob/master/source/minted.sty#L1136

**Comment by davidcarlisle** [comment]
> which uses h as the default placement specifier.

Oooh sorry, hadn't noticed that was the default!

In that case that's probably not ideal, as I say htp would be better than
ht, otherwise a full page listing can not be placed and will go to the end
of the docuemnt.
as both h and t are restricted to pages that have some normal text in
addition to the float.

David
(who as you may guess is just lurking here, I'm not involved in the minted
code:-)

**Comment by gpoore** [comment]
I'll switch it to `htp` for the next version.

**Comment by swoertz** [comment]
The default value for figures and tables in e.g., report.cls or article.cls are `tbp`. I would suggest to use this value.

**Comment by swoertz** [comment]
@D4Muck You can use `\floatplacement{listing}{tbp}` to override the default placement option meanwhile. This way you don't have to specify it for every listing.

**Comment by gpoore** [comment]
@swoertz That's a good point about defaults for figures and tables in standard classes.

**Comment by D4Muck** [comment]
@swoertz Thank you for the tip.

Personally I like it if listings are put 'here' so I am going for `htp`.

**Comment by swoertz** [comment]
@D4Muck I can understand that, but it should not be default in my opinion. If I don't want the listing to float, I don't have to put it into a floating-environment.

**Comment by gpoore** [comment]
The default `listing` placement is now `tbp` to parallel `figure` and `table`. I've added a section to the documentation on how to change the default placement.
