### ISSUE TITLE
escapeinside start/end token multiple characters

### ISSUE THREAD

**Issue by disconnect3d** [gpoore/minted#170]
Hey,

When using `lstlisting` there is a way to specify start/end token of multiple characters for `escapeinside`.
See e.g. https://tex.stackexchange.com/questions/197507/listings-escapeinside-option-is-not-working-for-me

Is there a way to do so for minted?

**Comment by gpoore** [comment]
In `minted`, `escapeinside` is implemented in Python within Pygments, rather than in LaTeX, so this isn't possible without adding features to Pygments or writing a Pygments wrapper in Python.

The current `escapeinside` has a number of issues, so it would be nice if someone could come up with a better Python implementation and add this at the same time.
