### ISSUE TITLE
Emergency stop with no information (minted 2.5 w/ MikTex 2.9.6400)

### ISSUE THREAD

**Issue by dtrent1** [gpoore/minted#175]
Freshly updated MikTex environment today. A basic script fails with an emergency stop error but other than that there is not much information. Minted was working fine before upgrading MikTex packages to their latest build (2.9.6400) this afternoon. I am running Pyhton 3.5.3 and Pygments 2.2.0.

tex document:
```tex
\documentclass{article}
\usepackage{minted}

\begin{document}
	\begin{minted}[mathescape,
	linenos,
	numbersep=5pt,
	gobble=2,
	frame=lines,
	framesep=2mm]{csharp}
	string title = "This is a Unicode π in the sky"
	/*
	Defined as $\pi=\lim_{n\to\infty}\frac{P_n}{d}$ where $P$ is the perimeter
	of an $n$-sided regular polygon circumscribing a
	circle of diameter $d$.
	*/
	const double pi = 3.1415926535
	\end{minted}
\end{document}
```

Messages:
```
Process started: pdflatex.exe -synctex=1 -interaction=nonstopmode "document".tex  --shell-escape
"exist" was unexpected at this time.
"^%i" was unexpected at this time.
Process exited with error(s)
```

Log File attached:
[log.txt](https://github.com/gpoore/minted/files/1201663/log.txt)

**Comment by gpoore** [comment]
This works with an up-to-date TeX Live installation under Windows. I tried older MiKTeX and it worked, then it failed on updating to 2.9.6400, which replicates your case.

MiKTeX 2.9.6400 also fails in the same way with the `minted1` package (old `minted` version 1.0), which indicates that this is not due to any changes in `minted`. This could be a bug in one of the other packages that `minted` depends on (unlikely, since updated TeX Live works), or a bug (or feature change) in the most recent MiKTeX. I'd recommend switching back to the earlier MiKTeX, or switching to TeX Live. Unfortunately, I don't have any suggestions for further debugging, other than to wait a few days to see whether `minted` stops working under TeX Live...if it keeps working under TeX Live, then this is almost certainly a MiKTeX issue.

**Comment by gpoore** [comment]
I just updated TeX Live and MiKTeX (both under Windows), and the error is still only occurring with MiKTeX. So this does appear to be a MiKTeX bug. You might report it to MiKTeX: https://miktex.org/help.

**Comment by u-fischer** [comment]
I made a bug report today https://sourceforge.net/p/miktex/bugs/2622/

**Comment by gpoore** [comment]
The MiKTeX site is showing that the bug is now fixed, and everything worked correctly after I updated MiKTeX, so I'm closing this.
