### ISSUE TITLE
Minted touches the source folder despite setting cache to false or cachedir to a different path

### ISSUE THREAD

**Issue by geyang** [gpoore/minted#177]
Hi,

Thanks for this package! 

In my work flow, I use `fswatch` to watch a source folder for file updates, and then generate all of the meta file and outputs to a different build folder.

Somehow when minted is used with the following parameters, it still "touches" the source folder, and triggers 2 ~ 5 `fswatch` file updates. The workflow works as long as i don't use minted.

Do you have any insight in why this is happening? 

Thanks!

```tex
% latex header
\setminted{fontsize=\small,baselinestretch=1}
```

```makefile
WORK_DIRECTORY=./source
MAIN_FILE=maml_note.tex
OUTPUT_DIRECTORY = ../build
WATCH_DIRECTORY=./source

default:
	make compile --ignore-errors
	mkdir -p build
#	compile twice for the table of contents to show.
	make compile --ignore-errors
	make clean
compile:
	bash -c "cd '$(WORK_DIRECTORY)' && pdflatex -interaction=nonstopmode -shell-escape -output-director '$(OUTPUT_DIRECTORY)' '$(MAIN_FILE)'"
clean:
	bash -c "cd '$(work_directory)' && \
    find -E ./ -regex '.*\.(aux|lof|log|lot|out|toc)' -type f -delete"
watch:
	echo "Watching for file changes inside $(WORK_DIRECTORY)"
	fswatch -o '$(WATCH_DIRECTORY)' | xargs -n1 -I{} make
watch-test:
	fswatch -0 -o '$(WATCH_DIRECTORY)'
```

**To Reproduce**

in one terminal window, run `make watch-test` to watch the folder
in another terminal window, run `make default` and it triggers event in the first terminal despite that there isn't any file generated in the source folder, and that the cache is set to a different folder.

Ge

**Comment by gpoore** [comment]
If you are compiling a file `source.tex`, then a temporary file `source.pyg` (and possibly also `source.aex` and `source.out.pyg`, depending on settings) will be created in the same directory as `source.tex`. The location of the temp files is independent of `cache`, `cachedir`, `-output-directory`, and any similar settings. By default, LaTeX packages can only write files in the source directory or its subdirectories. This prevents a malicious `.tex` file from overwriting arbitrary system files. The `.aux` and `.log` are not package-generated temp files and are treated specially, which is why they can be relocated with `-output-directory`.

I would recommend having your build setup only watch the relevant `.tex` and other files, or alternatively, configure it to ignore the `minted`-specific temp files in the source file directory.

**Comment by episodeyang** [comment]
@gpoore Thanks for your explaination! 

I took a look at the files that triggers `fswatch` during compilation. It looks like:
- the two temporary files that are created inside the `./source` folder are `*.w18` and `*.aex`
- **not** the `*.gyp` file you mentioned early. The `*.gyp` files are generated correctly inside the build folder without touching `./source`.

Do you know what these two files do? (`*.w18` and `*.aex`)

![screenshot 2017-08-14 16 12 03](https://user-images.githubusercontent.com/630490/29293096-5a57bfa6-810f-11e7-80fc-7cc061fe8d2f.png)

**Comment by episodeyang** [comment]
Here is an updated watch script that filters away the w18 and aex files.

```makefile
WORK_DIRECTORY=./source
MAIN_FILE=maml_note.tex
OUTPUT_DIRECTORY = ../build
WATCH_DIRECTORY=./source

default:
	mkdir -p build
	make compile --ignore-errors
#	compile twice for the table of contents to show.
	make compile --ignore-errors
	make clean
#	sleep 1
compile:
	bash -c "cd '$(WORK_DIRECTORY)' && pdflatex -interaction=nonstopmode -shell-escape -output-director '$(OUTPUT_DIRECTORY)' '$(MAIN_FILE)'"
clean:
	bash -c "cd '$(WORK_DIRECTORY)' && \
    find -E ./ -regex '.*\.(aux|lof|log|lot|out|toc)' -type f -delete"
watch:
	echo "Watching for file changes inside $(WORK_DIRECTORY)"
	fswatch -o -e '\.(pyg|aex|w18)$$' -E '$(WATCH_DIRECTORY)' | xargs -n1 -I{} make
watch-test:
	fswatch -0 -e '\.(pyg|aex|w18)$$' -E '$(WATCH_DIRECTORY)'

```

**Comment by gpoore** [comment]
The `.aex` is created by `minted` in determining whether Pygments is installed. The `.w18` is created by the `ifplatform` package (which `minted` loads) in the process of determining the operating system.

**Comment by episodeyang** [comment]
I see, since the folder watch doesn't detect the other temp files that minted generates, would there be any technical reasons these files have to be in the source folder?

**Comment by gpoore** [comment]
By default, LaTeX packages can only write files in the source directory or its subdirectories. So all of the files must be in the source folder. If the watching program doesn't detect the other temp files, that's probably just because there is a time delay between the creation of the `.aex` and `.w18` files, and the creation of the other files. They will all be in the source directory. But typically you won't see any of them, because they only exist while LaTeX is running; they are cleaned up before it exits.
