### ISSUE TITLE
Why does breaksymbol not work in mintinline ?

### ISSUE THREAD

**Issue by ysalmon** [gpoore/minted#178]
The minted manual states, regarding ```breaksymbolleft``` and so on, that "none of these options applies to \mintinline, since they are not relevant in the inline context."

I do not understand the soundness of this assumption. Inline code may very well span over two lines (and minted actually allows this) and I do not see why visual clues that it happens would be useless.

Students who are not yet familiar with the syntax of the language cannot easily determine when pieces of code on two successive lines are in fact a single statement. Moreover, having a symbol for line break in environments but not in inline code seems inconsistent in terms of presentation.

**Comment by gpoore** [comment]
Environments may contain multiple lines of code, so when a line is wrapped, it is necessary to have a break symbol to indicate that wrapping has taken place.

`\mintinline` is meant for inline code within a paragraph that is otherwise normal text. In that context, it is not possible to represent multiple lines of code with literal line breaks; an environment would be required for that. So any code that is wrapped within a paragraph of otherwise normal text is clearly wrapped rather than containing multiple lines. Line breaking is not the default, so it can be left disabled in any cases when the intended audience might misinterpret it.

**Comment by ysalmon** [comment]
I disagree on the idea that it is not useful to have a linebreak symbol in inline text. For example, the line break may at the same time be a page break, and it is nice to the reader to give him/her a visual clue that the code continues on the next page.

Plus, explaining to readers that "documents will have this symbol to mean that the code continues on the next line, but only in out-of-text code snippets" is a source of confusion, because it is not consistent.

**Comment by gpoore** [comment]
In the page break case, the lack of a period after the code could indicate that it isn't complete. If not having a break symbol inline does cause confusion, then it is always possible to force inline code not to have breaks, or to use an environment instead and avoid inline code.

If someone wants to submit a patch that adds support for a break symbol for inline code, I will be happy to consider it. However, this isn't something I will implement myself. Getting line breaking symbols working with just code was quite complex, and I expect that trying to do that with a mix of code and normal text may be an order of magnitude more difficult and have a lot of edge cases.
