### ISSUE TITLE
.pyg not found when using texi2pdf

### ISSUE THREAD

**Issue by galipnik** [gpoore/minted#186]
I have the following problem: I am using minted and it works perfectly when I run it with `pdflatex -shell-escape test.tex`. However, there is an error when I use `texi2pdf --shell-escape test.tex`, namely `tar: skript.pyg: Cannot stat: No such file or directory`. I have found the option `kpsewhich`, but it does not work either. Can anybody help?

**Comment by gpoore** [comment]
I'd suggest trying a simple document with a single `minted` environment (or `\inputminted`, depending on what you're doing), and seeing if you can get that to work or at least get a different error message. It looks like `tar` is being invoked on the temporary `.pyg` file, which is strange. I don't really have any `texi2pdf` experience, so my ability to help with this is limited.

**Comment by galipnik** [comment]
I have tested the simple document above, and: everything fine with pdflatex, same error message when I use texi2pdf, namely `tar: test.pyg: Cannot stat: No such file or directory`.
__________
`\documentclass{article}
\usepackage{minted}

\begin{document}
\begin{minted}{python}
a = 1
\end{minted}
\end{document}`

**Comment by gpoore** [comment]
It looks like this is due to the way that `texi2pdf` handles temporary files. `minted` automatically cleans up its temporary files.  `texi2pdf` seems to assume that any temporary file that is ever created will still exist at the end of the run, so it can invoke `tar` on all such files and relocate them. It's possible to disable `minted`'s temp file cleanup by adding something like `\renewcommand{\DeleteFile}[2][]{}` after the `\usepackage{minted}`.

**Comment by galipnik** [comment]
That works. Thanks!
