### ISSUE TITLE
Add support for PlantUML execution

### ISSUE THREAD

**Issue by koppor** [gpoore/minted#191]
PlantUML is a great tool to generate UML diagrams. Similar to pygments, one has to call an external executable. It supports [converting to latex](http://plantuml.com/latex)

Example:

```
@startuml
Bob -> Alice: hello
return Ok
@enduml
```

becomes:

![grafik](https://user-images.githubusercontent.com/1366654/36452785-16d8fa2a-1696-11e8-9cdd-9f9d580076a7.png)

Would it be possible to extend minted to support plantuml, too? I know that this is more than syntax highlighting. I think, however, that the treatment of executing an external tool and caching output remains very similar.

**Comment by gpoore** [comment]
This wouldn't really be appropriate for `minted`, since `minted` is focused on syntax highlighting. But the same sort of approach to caching etc. would be useful.

It might be possible to add support for something like this to [`pythontex`](https://github.com/gpoore/pythontex), which is focused on executing code in a LaTeX document. That wouldn't be a perfect fit, because this is a little different from code execution, but it would probably be possible to get something to work.

What is really needed is a package that generalizes `pythontex`, to allow arbitrary text processing or code execution with external tools and built-in caching. I've been very slowly working toward something like that for a few years, but unfortunately it's a big project and my time has been limited, so I'm not close to having anything that works yet.
