### ISSUE TITLE
Entire code block indented

### ISSUE THREAD

**Issue by Spirits-** [gpoore/minted#196]
I'm using VS Code with the Latex Workshop extension, previously the code looked fine, now suddenly everything is moved by a few tabs

<img width="373" alt="screenshot" src="https://user-images.githubusercontent.com/9485623/37864868-b01fcbcc-2f74-11e8-962e-d73f5ea52828.PNG">

This is how it looks now. The Tex code looks like this:

```
\begin{minted}{java}
            x = 10;
            if(x > 15){
                System.out.println("Success!");
            }
        \end{minted}
```
And the preamble:
```
\setminted{
        frame=lines,    
        framesep=2mm,
        baselinestretch=1.2,
        %bgcolor=background,
        linenos,
        breaklines=true
    }
```

Tex Workshop (the module adding compatibility to VC Code for Latex) has been recently updated to a new major version and this wasn't happening before. Is there a fix?

**Comment by gpoore** [comment]
If you are indenting code in the `.tex` source, but don't want any indentation in the `.pdf` output, then you probably want to use `autogobble` in `\setminted`. Depending on what you're doing, `gobble` would be an alternative. I don't know how Latex Workshop would be affecting this sort of thing.

**Comment by Spirits-** [comment]
Adding the `autogobble` in the preamble has no effect at all. Besides, I want tabs in the pdf, I just don't want all the code indented. I'd like it to start normally on the left.

**Comment by gpoore** [comment]
If using `\setminted{autogobble}` has no effect, then something else isn't working. You can also use `\begin{minted}[autogobble]{java}` to limit the effect to a single block of code.

Indentation of `\begin{minted}` has absolutely no effect on `autogobble`. `autogobble` always uses absolute rather than relative indentation.

If you're sure that Latex Workshop is the only thing that has changed in your setup, then I would recommend looking into that as the likely source of your issues. I don't use it, so I can't provide any suggestions for what it might be doing to cause this.

**Comment by Spirits-** [comment]
I've gotten autogobble to work. I forgot to add a comma in the preamble which made minted ignore the keyword. Apologies. The code now seems to indent succesfully. Thanks for your help. The only interesting thing is that previously I didn't need `autogobble` for the code to look normal in the pdf.

**Comment by gpoore** [comment]
@derlin The current version of `minted` works correctly. I would need more detail about your specific case to offer any suggestions.
