### ISSUE TITLE
Numbers in styles

### ISSUE THREAD

**Issue by Lelio-Brun** [gpoore/minted#210]
Using styles with numbers in their names does not work, eg. styles from [base16-pygments](https://github.com/idleberg/base16-pygments).
So
```latex
\usemintedstyle{base16-classic-light}
```
won't work, default style is used instead.

Actually one can tweak the *.py files in order to use roman style numbering, but it's kind of hacky.

**Comment by gpoore** [comment]
The problem is that styles are based on macros with names of the form `\PYG<style>`, and numbers aren't allowed in macro names. I have gotten hyphens and underscores in macro names to work, but that's only due to the fact that the particular form of the style definitions allows for catcode trickery that probably wouldn't work for numbers.

I think the solution is to keep the literal style names (current system) and also introduce a sanitized version in which numbers are replaced (maybe using the `xstring` package?) by words (so `baseonesix-classic-light`). The literal style would be passed to Pygments to find the style, but the sanitized version would be used for creating the stylesheet. I'm in the midst of several other projects at the moment, so I don't know when I can get to this. Feel free to make an attempt if you want.
