### ISSUE TITLE
how to make an zebra effect on linenumbers and contents

### ISSUE THREAD

**Issue by xiaoleeza** [gpoore/minted#211]
[problem at tex.stackexchange.com](https://tex.stackexchange.com/questions/445258/one-tcbcolorbox-with-alternative-color-in-different-lines)

I am using highlightlines={1,3,5,7,...}, but this is not convenient when there is too many lines.

**Comment by gpoore** [comment]
Take a look at https://github.com/gpoore/fvextra/issues/8. `minted` uses `fvextra` internally. You could use the linked demo implementation for now, but would need to use `\fvset` rather than `\setminted` to specify options since the demo doesn't implement a wrapper for `minted`. `fvextra` will add official support for this at some point (then I'll add `minted` support), but I don't know when that will be.

**Comment by xiaoleeza** [comment]
Thanks you very much for your response. Waiting for your good news.

**Comment by muzimuzhi** [comment]
By the way, if you want use new `fvextra` options introduced in the demo [gpoore/fvextra#8](https://github.com/gpoore/fvextra/issues/8) through normal `minted` ways, defining those options in `minted` could help. Take a look at the following  example:

```latex
\documentclass{article}
\usepackage{minted}

% names of new added options might change
\makeatletter
\minted@def@optfv{highlightlinenumbercolor}
\minted@def@optfv{linenumberwidth}
\makeatother

\setminted{
  linenos,
  highlightcolor={cyan!10, cyan!15},
  highlightlinenumbercolor={yellow!30, yellow!40},
  numbersep=3pt
}

\begin{document}
\begin{minted}{c}
int main() {
  printf("hello, world");
return 0;
\end{minted}
\end{document}
```
Output:
![image](https://user-images.githubusercontent.com/6376638/44138256-e4f4f974-a0a5-11e8-8224-df4ee7dcb55f.png)
