### ISSUE TITLE
Minted ignored page break

### ISSUE THREAD

**Issue by azzamsa** [gpoore/minted#219]
Hi.

I keep this problem with me more than a months, I have to solve this manually by adding `\par\null\par` as much as possible or `\newpage` to add space until minted doesn't break.

I don't know what's going on. Because in some part nothing wrong with minted. but in other, minted ignored the page break.

This is the same pictures I asked in [Tex SE](https://tex.stackexchange.com/questions/456192/minted-ignored-page-break) sadly with no repy.

Minted ignored the page break

![img1](https://i.stack.imgur.com/wME5i.png)

Minted knows the page break

![img2](https://i.stack.imgur.com/X874q.png)

I also asked this probem at [r/latex](https://www.reddit.com/r/LaTeX/comments/9sax2f/longtable_and_minted_ignore_page_geometry/) also with no reply :(.

This problem doesn't occur for page with minimal longtable and minted : [mwe](https://paste.debian.net/1049495/). But it's occured when I use many longtable and minted: [mwe](https://paste.debian.net/1049496/).

Thank you in advance.

**Comment by gpoore** [comment]
If you can get this to happen with a simple 2-page document, I can take a look. There may be a package clash or something similar. However, I've looked at your two examples, and can't do anything with the document where you say there are issues, because it is very long and involves a lot of separate things like images that prevent me from compiling it properly. So if you can find a 2-page example, I may be able to help, but unfortunately there isn't anything I can suggest right now.

**Comment by azzamsa** [comment]
I try can't reproduce it with my new [MWE](https://gist.github.com/azzamsa/f77c3e4b930291be0c4fcea49af43557). All minted code placed correctly, just one bad longtable ignored pagebreak. If something bad happened, I will try to make new issue with complete and runnable MWE. Thanks a lot :)

![2018-11-14-19 27 10](https://user-images.githubusercontent.com/17734314/48482637-c9bf2400-e843-11e8-99d0-6a3c86fa8b7b.png)
