### ISSUE TITLE
Using minted with KOMA-Script yields warning

### ISSUE THREAD

**Issue by Quintus** [gpoore/minted#22]
Hi there,

using `minted` with the KOMA-Script classes (which are quite popular in Europe) yields the following warning:

~~~~~~~~~~~~~~~~~~~~
Class scrbook Warning: \float@addtolists detected!
(scrbook)              You should use the features of package `tocbasic'
(scrbook)              instead of \float@addtolists.
(scrbook)              Support for \float@addtolists may be removed from
(scrbook)              `scrbook' soon .
~~~~~~~~~~~~~~~~~~~~

Here’s a minimal example reproducing the above warning:

~~~~~~~~~~~~~~~~~~~~ latex
\documentclass[a4paper,11pt]{scrbook}

\usepackage{minted}

\begin{document}
\chapter{test}
\begin{minted}{ruby}
def foo
  "foo"
end
\end{minted}
\end{document}
~~~~~~~~~~~~~~~~~~~~

If you comment out the `\chapter` command, the warning vanishes. The same goes for changing from `scrbook` to the LaTeX default `book` (which is not an option for me).

Probably `minted` somehow redefines `\chapter` in a way that may work on the default LaTeX classes, but doesn’t in other ones?

Vale,
Marvin

**Comment by gpoore** [comment]
`minted` uses the `float` package to produce floated listings, but KOMA-Script uses a different mechanism to create floats. This may be fixed by loading the `scrhack` package *after* `minted`. The `scrhack` package patches the float treatment of other packages to be compatible with KOMA-Script.

I have added a note on this to the FAQ in the next version of the documentation. Also, recent versions of KOMA-Script now mention the `scrhack` solution in the warning message.

**Comment by Mr-Tao** [comment]
FAQ suggests using `newfloat` option as an alternative to `scrhack` to silence this warning. However, without `scrhack` I am getting the warning regardless of the `newfloat` option.

**Comment by gpoore** [comment]
@Mr-Tao I'm not getting any warnings with `newfloat` under TeX Live 2018.
