### ISSUE TITLE
Working around escapeinside fragility

### ISSUE THREAD

**Issue by lol768** [gpoore/minted#230]
As has been explored here before, it is well known that `escapeinside` works poorly with some lexers.

In the past I've worked around this by highlighting code in my desired language, taking the generated LaTeX code in `_minted-document` and then hardcoding it as-is in my document. This obviously is a PITA if I need to change the underlying code that has been highlighted, but it's done the job for me up until now.

Here's an example of the sort of thing I've been doing:

```tex
\begin{Verbatim}[commandchars=\\\{\}]
\PYG{k+kd}{public} \PYG{n}{String} \PYG{n+nf}{lookupUserNameByToken}\PYG{o}{(}\PYG{n}{String} \PYG{n}{token}\PYG{o}{)} \PYG{k+kd}{throws} \PYG{n}{SQLException} \PYG{o}{\PYGZob{}}
    \PYG{n}{Statement} \PYG{n}{stmt} \PYG{o}{=} \PYG{n}{connection}\PYG{o}{.}\PYG{n+na}{createStatement}\PYG{o}{(}\PYG{o}{)}\PYG{o}{;}
    \PYG{n}{String} \PYG{n}{query} \PYG{o}{=} \PYG{l+s}{\PYGZdq{}select * from users where \PYGZdq{}}\PYG{o}{;}
    % begin custom code
    \colorbox{red}{\textcolor{white}{\faExclamationTriangle{} \PYG{n}{query} \PYG{o}{+=} \PYG{l+s}{\PYGZdq{} token = '\PYGZdq{}}}}
    % end custom code
    \PYG{n}{ResultSet} \PYG{n}{rs} \PYG{o}{=} \PYG{n}{stmt}\PYG{o}{.}\PYG{n+na}{executeQuery}\PYG{o}{(}\PYG{n}{sql}\PYG{o}{)}\PYG{o}{;}
    \PYG{k}{if} \PYG{o}{(}\PYG{n}{rs}\PYG{o}{.}\PYG{n+na}{next}\PYG{o}{(}\PYG{o}{)}\PYG{o}{)} \PYG{o}{\PYGZob{}}
        \PYG{k}{return} \PYG{n}{rs}\PYG{o}{.}\PYG{n+na}{getString}\PYG{o}{(}\PYG{l+s}{\PYGZdq{}name\PYGZdq{}}\PYG{o}{)}\PYG{o}{;}
    \PYG{o}{\PYGZcb{}}
    \PYG{k}{return} \PYG{k+kc}{null}\PYG{o}{;}
\PYG{o}{\PYGZcb{}}
\end{Verbatim}
```
Now, the problem I have with this is:

* It doesn't render correctly unless the code has already been highlighted by `minted`. I think some of the commands/token colours end up undefined/lazily loaded and so I need to always include the original code somewhere in the document.
* It doesn't respect the `\usemintedstyle{idseven}` directive I have in the preamble and just uses the default syntax highlighting style.

What can I do to get this to work consistently, using the same style set in the document preamble? Where do the style definitions come from? And is there any way I can remove the need for the first point?

----

To illustrate what I mean, here's a screenshot:

![](https://lol768.com/i/DisfranchisingTrademarkingBurrWristwatches)

First code listing is the real `\begin{minted}{java}` output, which uses the document style as one would expect. Second listing, in the grey box, uses the code above. Note that the colours are incorrect, and it appears to be using the default Pygments style.

**Comment by lol768** [comment]
> It doesn't respect the `\usemintedstyle{idseven}` directive I have in the preamble and just uses the default syntax highlighting style.

If I replace instances of `\PYG` with `\PYGidseven`, this works :tada: - so I think I've answered this one myself. It's hacky, but it works.

**Comment by gpoore** [comment]
* For the highlighting to work, you need the highlighting commands (`\PYG`, etc.) from Pygments. `minted` generates the command definitions using Pygments, then saves the definitions in the `_minted*` directory. These are generated, saved, and loaded on an as-needed basis. You should be able to copy the style definition files (both your style, plus the PYG default), then `\input` them, and not need `minted` at all if you are just hardcoding the Pygments output.

* All code is highlighted with the default style using `\PYG` prefixed commands. Then, right before typesetting, `\let\PYG\PYG<style>` is used to switch to the appropriate style. In your case that would be `\let\PYG\PYGidseven`. This allows the style to be changed without re-running Pygments, which helps with caching. If you have a file that doesn't need `minted` at all, with only hardcoded content, you could just add this command to your preamble. Otherwise, you could use it right before `\begin{Verbatim}`, and then wrap everything in a `\begingroup...\endgroup`.

**Comment by lol768** [comment]
Many thanks for that @gpoore
