### ISSUE TITLE
strang errror: "Runaway argument?" on file to listing task

### ISSUE THREAD

**Issue by lx-931203** [gpoore/minted#245]
Hello,

```sh
Runaway argument?
    \PYGZhy {}o \PYGZdl {}\PYG {esc}{ \}^^M\PYG {esc}{    -flto \}^^M\ETC.
! File ended while scanning use of \FancyVerbGetLine.
<inserted text> 
                \par 
l.28     \codefile[tabsize=2, obeytabs]{codefile}
                                            
? x
No pages of output.
Transcript written on handout.log.
```

problem code
```
%.a: %.o
  ar -rc $@ $<
  ar -t $@
  nm $@
```

Can someone help to fix it?

**Comment by gpoore** [comment]
The code that is causing issues involves `-o` and `-flto`, which are not included in the code you list.

To get help with this, you will need to give a complete minimal example, that is, a complete document that produces the problem that is also as short as possible.

**Comment by lx-931203** [comment]
Thanks for reply, example is [here](https://drive.google.com/open?id=1_VaVbeFBsquDLhm-GAdCotXqrmQxx2Fd)

try to run with `pdflatex -shell-escape doc.tex`

**Comment by gpoore** [comment]
You're using `escapeinside=@@`. This treats everything between `@` symbols as LaTeX markup rather than as code. If you do need to use `escapeinside` to include LaTeX markup within your code, the escape symbols (`@` in this case) both need to be on the same line. Currently, `minted` is trying to escape to LaTeX markup across multiple lines, which is resulting in errors.

**Comment by lx-931203** [comment]
Yes, thank you. I am feeling stupid.

Sorry for waste of your time.

P.S. Excellent support, by the way.
