### ISSUE TITLE
Autodetect if pygments/pygmentize is installed

### ISSUE THREAD

**Issue by FranzAtGithub** [gpoore/minted#255]
Hello,

I am writing LaTeX documents with multiple other people.
I am not sure if all of them have `pygments` (or even `python`) installed on their machine.
I am also not sure if all run `--shell-escape`.

Is it possible to detect all/some of the potential problems from within LaTeX and set the `draft` value of `minted` accordingly?

**Comment by gpoore** [comment]
All of those things are currently detected and result in errors. The easiest option might be to use `draft` for the shared document.

If you want to look into creating a new package option to do this, you would want to look at `\TestAppExists` and `\ifnum\pdf@shellescape`. Unfortunately, it is very difficult to try to turn `draft` on or off after `minted` has been loaded, because many things are conditionally defined based on `draft` mode, so a new package option would really be needed. This can't be accomplished by adding a few lines of patch code after loading `minted`. 

Here's the part of `minted.sty` that checks these things. 
```latex
\AtEndOfPackage{%
  \ifthenelse{\boolean{minted@draft}}%
   {}%
   {%
    \ifthenelse{\boolean{minted@frozencache}}{}{%
      \ifnum\pdf@shellescape=1\relax\else
        \PackageError{minted}%
         {You must invoke LaTeX with the
          -shell-escape flag}%
         {Pass the -shell-escape flag to LaTeX. Refer to the minted.sty
          documentation for more information.}%
      \fi}%
   }%
}
\AtEndPreamble{%
  \ifthenelse{\boolean{minted@draft}}%
   {}%
   {%
    \ifthenelse{\boolean{minted@frozencache}}{}{%
      \TestAppExists{\MintedPygmentize}%
      \ifAppExists\else
        \PackageError{minted}%
         {You must have `pygmentize' installed
          to use this package}%
         {Refer to the installation instructions in the minted
          documentation for more information.}%
      \fi}%
  }%
}
```

**Comment by FranzAtGithub** [comment]
Why would I have to change the `draft`-option after `minted` is loaded?
Can I not use `\TestAppExists` and `\pdf@shellexcap` before loading the package?

**Comment by gpoore** [comment]
My standard approach in a case like this would be to look for a way to load `minted` with one set of options, and then change the options after loading if needed. But that won't really work for `draft` because so much depends on it.

You could try using the checks before loading the package. You could copy the definition of `\TestAppExists` out of `minted`, and use that plus the shell escape checks to load `minted` with or without `draft` based on what is available. You would need to rename the copied `\TestAppExists`, etc. so it wouldn't conflict with `minted`.  That's probably much easier than adding a new option.

**Comment by FranzAtGithub** [comment]
Ok. I am not very experienced in LaTeX-package programming.
I assume I would copy from line176 (https://github.com/gpoore/minted/blob/master/source/minted.sty#L176) to 202 and rename till I get no more errors?

Ty, for all your help btw.

**Comment by gpoore** [comment]
Something like this should work:

```latex
\documentclass{article}

\usepackage{pdftexcmds}
\usepackage{shellesc}
\usepackage{ifthen}
\usepackage{ifplatform}
\usepackage{xstring}
\makeatletter
\StrSubstitute{\jobname}{ }{_}[\minted@jobname]
\StrSubstitute{\minted@jobname}{*}{_}[\minted@jobname]
\StrSubstitute{\minted@jobname}{"}{}[\minted@jobname]
\StrSubstitute{\minted@jobname}{'}{_}[\minted@jobname]
\ifwindows
  \providecommand{\DeleteFile}[2][]{%
    \ifthenelse{\equal{#1}{}}%
      {\IfFileExists{#2}{\ShellEscape{del #2}}{}}%
      {\IfFileExists{#1/#2}{%
        \StrSubstitute{#1}{/}{\@backslashchar}[\minted@windir]
        \ShellEscape{del \minted@windir\@backslashchar #2}}{}}}
\else
  \providecommand{\DeleteFile}[2][]{%
    \ifthenelse{\equal{#1}{}}%
      {\IfFileExists{#2}{\ShellEscape{rm #2}}{}}%
      {\IfFileExists{#1/#2}{\ShellEscape{rm #1/#2}}{}}}
\fi
\newboolean{AppExistsCopy}
\newread\minted@appexistsfile
\newcommand{\TestAppExistsCopy}[1]{
  \ifwindows
    \DeleteFile{\minted@jobname.aex}
    \ShellEscape{for \string^\@percentchar i in (#1.exe #1.bat #1.cmd)
      do set > \minted@jobname.aex <nul: /p
      x=\string^\@percentchar \string~$PATH:i>> \minted@jobname.aex}
    %$ <- balance syntax highlighting
    \immediate\openin\minted@appexistsfile\minted@jobname.aex
    \expandafter\def\expandafter\@tmp@cr\expandafter{\the\endlinechar}
    \endlinechar=-1\relax
    \readline\minted@appexistsfile to \minted@apppathifexists
    \endlinechar=\@tmp@cr
    \ifthenelse{\equal{\minted@apppathifexists}{}}
     {\AppExistsCopyfalse}
     {\AppExistsCopytrue}
    \immediate\closein\minted@appexistsfile
    \DeleteFile{\minted@jobname.aex}
  \else
    \ShellEscape{which #1 && touch \minted@jobname.aex}
    \IfFileExists{\minted@jobname.aex}
      {\AppExistsCopytrue
        \DeleteFile{\minted@jobname.aex}}
      {\AppExistsCopyfalse}
  \fi
}
\ifnum\pdf@shellescape=1\relax
  \expandafter\@firstoftwo
\else
  \expandafter\@secondoftwo
\fi
 {\TestAppExistsCopy{pygmentize}
   \ifAppExistsCopy
     \expandafter\@firstoftwo
   \else
     \expandafter\@secondoftwo
   \fi
    {\usepackage{minted}}
    {\usepackage[draft]{minted}}}
 {\usepackage[draft]{minted}}
\makeatother



\begin{document}

\begin{minted}{python}
print('String')
\end{minted}

\end{document}

```

**Comment by FranzAtGithub** [comment]
wow wonderful, thanks a lot!

**Comment by muzimuzhi** [comment]
If possible, overleaf.com is a good place to write in latex with co-authors. It always use -shell-escape, and supports pygments.
