### ISSUE TITLE
\setmintedinline does not work properly

### ISSUE THREAD

**Issue by oyvindskaaden** [gpoore/minted#258]
When trying to set global options for minted, i stumbled across a bug. 

I tried setting the global settings via
```latex
\setminted{mathescape,
               linenos,
               numbersep=5pt,
               gobble=2,
               frame=lines,
               framesep=2mm}
```
and then I wanted to remove the gobble for inline blocks and created a inline for python and html
```latex
\setmintedinline{gobble=0}
\newmintinline[python]{python}{showspaces,gobble=0}
\newmintinline[html]{html}{showspaces,gobble=0}
```

The last commands does not remove the gobble. The only solution i can find is to omit the `gobble` setting globally and setting it for each codeblock.

**Comment by gpoore** [comment]
The issue here is that `minted` gives Pygments the gobble setting multiple times (once for global, once for inline, and once for new commands: `-F gobble:n=2 -F gobble:n=0 -F gobble:n=0`), and Pygments is apparently using the first value it receives (global value) rather than the last (command value). Fixing this may require a complete redesign of the Pygments interface within `minted`.

You might look at `autogobble` if that works for your purposes.

**Comment by oyvindskaaden** [comment]
Ok, thanks! :smile: 

I'll try the autogobble :+1:

**Comment by gpoore** [comment]
This entire class of issues is eliminated in `minted` v3.0, which is available as a [beta on GitHub](https://github.com/gpoore/minted/tree/v3-dev) and will have a final release soon.
