### ISSUE TITLE
strip all leading space

### ISSUE THREAD

**Issue by cat-master** [gpoore/minted#266]
Hello.

Does `minted` has an option to remove all leading space for any line string?

Yes, we can use `gobble` option and manually specify spaces amount to omit.
Option `autogobble` is too-much "auto" - for example, when it see C-style curly braces or Python indent, it will not delete leading spacing for nested code.

Example can be demonstrated by two code files.

```groovy
plugins {
  id "org.springframework.boot" version "2.3.0.RELEASE"
  id "io.spring.dependency-management" version "1.0.9.RELEASE"
  id "java"
}
```

```tex
\documentclass{article}

\usepackage{minted}
\usepackage{parskip}

\newmintedfile[code]{text}{firstnumber=1,autogobble}

\begin{document}

Text.
\code[firstline=3, lastline=3]{build.gradle}
Text.
\code[firstline=4, lastline=4]{build.gradle}
Text.
\code[firstline=5, lastline=5]{build.gradle}
Text.
\code[firstline=4, lastline=5]{build.gradle}

\end{document}
```

Result file.
[document.pdf](https://github.com/gpoore/minted/files/4722769/document.pdf)

Can someone suggest solution?

**Comment by gpoore** [comment]
There is no option to do that. Here are a couple things you could look into if you want to try to implement something:

- Use `\ShellEsc` to create a temp file that is a copy of the original with all spaces stripped. Then use `\inputminted` on that.
- Define a custom version of `\FV@@Gobble` from `fancyvrb`, which handles `gobble` behind the scenes.
- Use LuaLaTeX to read in the code and strip the spaces, and wrap the result in `\begin{minted}`...`\end{minted}`
- Change `autogobble` in your local copy of `minted` so it uses `lstrip()` instead of `dedent()`.

**Comment by cat-master** [comment]
Thank you for reply.
