### ISSUE TITLE
Line-breaking for "text" lexer

### ISSUE THREAD

**Issue by 3isenHeiM** [gpoore/minted#311]
Hi,
I've troubles having line breaks when using the lexer `text` in minted.

The same sentence is not broken at the same place, when using `python` or `text` language, and I don't know how can I do it properly.

IMO a text block can be broken everywhere, but apparently it's not the case.

Here is a MWE (taken from my [question on TeX.se](https://tex.stackexchange.com/questions/618170/minted-language-text-doesnt-obey-to-breaklines?noredirect=1#comment1543798_618170)) : 

```
\documentclass[]{article}
\usepackage[showframe]{geometry}
\usepackage[T1]{fontenc}
\usepackage{minted}


\begin{document}
Here is a veeeeeryyyyy veeeeeryyyyy loooooooooong \texttt{mintinline} with a break,
\mintinline[breaklines, breakanywhere]{python}{very_long_class_name} because it uses the \textbf{Python} minted language.


Here is a veeeeeryyyyy veeeeeryyyyy loooooooooong \texttt{mintinline} with a break,
\mintinline[breaklines, breakanywhere]{text}{very_long_class_name} using the \textbf{text} minted language.
    
    
\end{document}
```

And here is the output : 

![](https://i.stack.imgur.com/27q7S.png)

How can I have a decent line break using the `text` language ?

**Comment by gpoore** [comment]
It looks like there's a bug in `minted`'s use of the line breaking features from `fvextra` that only shows up with the `text` lexer (missing `\FancyVerbBreakStart...\FancyVerbBreakStop` wrapping entire text, since text isn't inside token macros). I have a very long backlog of work on open source projects, so I have no idea when this can be fixed.

The best workaround for now is probably to use `\Verb`, which will be the special `\Verb` from `fvextra` when `minted` has been loaded: `\Verb[breaklines, breakanywhere]{very_long_class_name}`.

**Comment by 3isenHeiM** [comment]
The workaround works, thanks :)

**Comment by amine-aboufirass** [comment]
@gpoore The problem there is that you can't control `bgcolor` the way you do with `\setmintedinline`

**Comment by gpoore** [comment]
This is fixed by the newly reimplemented `\mintinline`.
