### ISSUE TITLE
Leading Chinese characters introduce unexpected boxes

### ISSUE THREAD

**Issue by zwz** [gpoore/minted#363]
Here is a MWE
```
\documentclass{ctexart}
\usepackage{minted}
\begin{document}
\begin{minted}{cpp}
测试#include <string>
中文int main(){
    return 0;    // 中文
}
\end{minted}
\end{document}
```
And here is the result.
![截屏2023-04-07 上午10 28 28](https://user-images.githubusercontent.com/897156/230528916-a663f2ef-41a1-429e-a71a-034aece8d153.png)

The 1st line`测试#` and 2nd line `中文` are in boxes.

**Comment by muzimuzhi** [comment]
You're using an outdated [`pygments`](https://pypi.org/project/Pygments/#history).

The C-family lexers in `pygments` learnt support for unicode identifiers (see https://github.com/pygments/pygments/pull/1848) since `pygments` [2.11.0](https://github.com/pygments/pygments/releases/tag/2.11.0), released in Dec, 2021.

With latest `pygments` is [2.14.0](https://github.com/pygments/pygments/releases/tag/2.14.0), released in Jan, 2023, your example gives (need either `xelatex` or `lualatex`)
![image](https://user-images.githubusercontent.com/6376638/230532801-66174db5-ee54-4f5f-acca-38b4b42a53ff.png)
(The thin red frame around `#` denotes an error token in default `pygments` style.)  You can check it on https://pygments.org/demo/ yourself.

**Comment by zwz** [comment]
Yes, I am using an old version.

Is the red frame around `#` expected?

**Comment by muzimuzhi** [comment]
> Is the red frame around `#` expected?

Yes. It marks an invalid (cpp) grammar.

**Comment by muzimuzhi** [comment]
> With latest `pygments` is [2.14.0](https://github.com/pygments/pygments/releases/tag/2.14.0), released in Jan, 2023, your example gives (need either `xelatex` or `lualatex`)
> ![image](https://user-images.githubusercontent.com/6376638/230532801-66174db5-ee54-4f5f-acca-38b4b42a53ff.png)

https://github.com/CTeX-org/ctex-kit/issues/580 contains some solutions to suppress the spacing between `中文` and `int`.

**Comment by zwz** [comment]
Thank you for the link.
