### ISSUE TITLE
Add an option to not show error boxes

### ISSUE THREAD

**Issue by Skgland** [gpoore/minted#374]
I was reminded by a recent comment on my [stackoverflow anser](https://tex.stackexchange.com/a/504621/161012), that it may be good to request this as a feature.

Basically, in some insances one might want to use for example greek letters for variable names to match the naming one uses for the mathematical equations. Currently doing so results in boxes around them as they are not valid variable names in most languages. Currently this requires a workaround as suggested in my SO Answe. It would help to have this as an official flag analog to `linebreaks=true` one might want to set `highlight_errors=false`.

Example images from the SO Question and other SO Ansers:

Before/`highlight_errors=true`: 

![image](https://github.com/gpoore/minted/assets/3877590/cf47444b-212b-4a6c-8770-b7b2814d57ce)

After/`highlight_errors=false`:

![image](https://github.com/gpoore/minted/assets/3877590/f2e12640-1a73-4f04-82d4-4c5ebe582959)

**Comment by muzimuzhi** [comment]
Could be part of the under development minted 3.0, by subclassing the style class and overwriting any border specifications used in error tokens (for example, the [`Error: "border:#FF0000"`](https://github.com/pygments/pygments/blob/4b14e3909b27be6c621ddf3532cf334214fb8aaf/pygments/styles/default.py#L75C9-L75C52) in `default` style.), when generating style definitions for some style for latex formatter.

For the specific python example in the linked SO question (also called TeX.SX question since it's a TeX community in Stack Exchange Network), since `pygments` has been supported unicode identifiers in Python 3 lexer for many years, it is now hard to reproduce that in `python` language.

Example below, run on overleaf.com with it's TeX Live 2015 mirror, shows that unicode identifiers are already supported in Pygments 2.0.2, [released Jan 20, 2015](https://github.com/pygments/pygments/blob/4b14e3909b27be6c621ddf3532cf334214fb8aaf/CHANGES#L1265). (The error boxes in the first `minted` env is expected, because at that time language `python` still points to Python 2, which doesn't have unicode identifiers support.)

Considering the linked TeX.SX question was asked in 2016, I infer the direct cause was that `python3` language should be used, rather than `python`.

```tex
\documentclass{article}
\usepackage{bashful}
\usepackage{fontspec}
% \setmonofont{Latin Modern Mono}

\usepackage{minted}

\begin{document}
\begin{minted}{python}
# python 2
def add(α, β):
    return α + β
\end{minted}

\begin{minted}{python3}
# python 3
def add(α, β):
    return α + β
\end{minted}

\ttfamily
\fmtname\space\fmtversion\par

\bash[stdout]
pygmentize -V
\END
\end{document}
```

![image](https://github.com/gpoore/minted/assets/6376638/eeed6e2e-7549-4bc1-afc9-5d8fe5a80202)
