### ISSUE TITLE
JSX highlighting is not working in overleaf

### ISSUE THREAD

**Issue by skittlesaur** [gpoore/minted#383]
Even though it's supported in [Pygments lexers](https://pygments.org/docs/lexers/), it doesn't seem to be working in overleaf.

I tried the following:

```latex
\begin{minted}{jsx}
const Component = () => {
  return <div>test</div>
}
\end{minted}
```

**Comment by muzimuzhi** [comment]
JSX lexer is [supported since pygments v2.17.0 (2023-11-18)](https://github.com/pygments/pygments/blob/17ec7ec23e28ceff859e6848bdcace4750434ba1/CHANGES#L57-L63), while Overleaf still uses [pygments v2.11.2 (2022-01-06)](https://pypi.org/project/Pygments/2.11.2/).

Run following example on Overleaf, using its TeX Live 2023 mirror, and you'll get "Pygments version 2.11.2, ...". To run it locally, you need to enable shell escape.
```tex
\documentclass{article}

\begin{document}
\input|"pygmentize -V"
\end{document}
```

**Comment by muzimuzhi** [comment]
Checked today (Sep 8, 2024), now Overleaf provides Pygments v2.15.1, newer than the one shown in this January, but still not new enough to support JSX lexer.

Currently, the newest release is Pygments [v2.18.0](https://github.com/pygments/pygments/releases/tag/2.18.0), released this May 4.

**Comment by STR1234** [comment]
If you want to integrate JSX/TSX support in the meantime, you can go with the solution from here: [](https://tex.stackexchange.com/questions/548454/custom-styles-for-minted-in-overleaf#:~:text=%5C-,begin,-%7Bminted%7D%7BPortugolStudioLexer.py) - only change I had to make, to get it to work was putting the loading statement into single quotes like this:`\newmintinline[typescriptinline]{'jsx.py:TsxLexer -x'}` - I also put the jsx.py into the root folder in my overleaf project. I would recommend setting it up like the stachexchange post suggests - ends up being a quite clean solution. I am using Overleaf with TeX Live Version 2024 btw. - had read another post where it stated that it only works with 2017 legacy but ended up seemingly being related to missing the single quotes. Hope this helps.
