### ISSUE TITLE
\mintline line break too late

### ISSUE THREAD

**Issue by Pfischi** [gpoore/minted#400]
When using `\mintinline` with a shell command which has a long url line breaking will kick in too late. Using a minted environment everything is ok.

Is there anyway to config \mintineline to break a little bit earlier so that the comment will not go over my margins?

![issue_minted](https://github.com/user-attachments/assets/468065f2-ba13-4231-bcb4-c89b090078da)

```
\documentclass[
    a4paper,
    parskip=half,
    fontsize=11pt,
]{scrartcl}

\usepackage[ngerman]{babel}
\usepackage{lmodern}
\usepackage{fontspec}
\usepackage[margin=2.5cm]{geometry}
\usepackage{minted}
\usepackage{showframe}

\begin{document}
\mintinline[breaklines, breakafter=-/\space\\]{bash}{bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered)}

\begin{minted}[breaklines, breakafter=-/\space\\]{bash}
bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered)
\end{minted}

\end{document}
```

**Comment by muzimuzhi** [comment]
The new `breakanywhereinlinestretch ` option in the developing version of `minted` may help, see https://github.com/gpoore/minted/issues/387#issuecomment-2336508832.

A more interesting question: given the same code to highlight and line width to typeset, why `\mintinline` and `minted` environment chose different break points?

A slightly simplified example:
```tex
\documentclass{article}
\usepackage[pass, showframe]{geometry}
\usepackage{minted}

\begin{document}
\noindent
\mintinline[breaklines, breakafter=-/\space\\]{bash}{bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered)}

\begin{minted}[breaklines, breakafter=-/\space\\]{bash}
bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered)
\end{minted}

% add "breaksymbolleft="
\begin{minted}[breaklines, breakafter=-/\space\\, breaksymbolleft=]{bash}
bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered)
\end{minted}
\end{document}
```

![image](https://github.com/user-attachments/assets/88fd1d88-8543-489e-b0ec-aaeea69d7ff4)

**Comment by gpoore** [comment]
Line break locations depend on hyphenation settings and various penalties related to line breaks. In a `Verbatim` environment, and thus `minted` environment as well, these are automatically modified since the environment contains the entire text. In the `\mintinline` case, some of the relevant settings cannot be modified within the `\mintinline` command, because these settings must be in place before a paragraph begins and thus cannot be modified within a command.

If breaks are acceptable at any location, not just at spaces and slashes, then `breakanywhere` with the new `breakanywhereinlinestretch` could work. That requires the beta version of `minted` v3.0 plus the dev version of `fvextra`.

In this case, adding something like `\emergencystretch=1em\relax` works. This could be in the preamble, if you want it for the entire document, or it could be localized like this:
```latex
\begingroup
\emergencystretch=1em\relax

\mintinline[breaklines, breakafter=-/\space\\,breakanywhereinlinestretch=1em]{bash}{bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered)}

\endgroup
```

**Comment by muzimuzhi** [comment]
> In the `\mintinline` case, some of the relevant settings cannot be modified within the `\mintinline` command, because these settings must be in place before a paragraph begins and thus cannot be modified within a command.

Ah TeX's paragraph-wide settings, again.

**Comment by Pfischi** [comment]
> 
> ```
> \begingroup
> \emergencystretch=1em\relax
> 
> \mintinline[breaklines, breakafter=-/\space\\,breakanywhereinlinestretch=1em]{bash}{bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered)}
> 
> \endgroup
> ```

Thx for the quick help. 
Using the new versions of minted and fvextra in combination with \\emergencystretch fixed my problem.
