### ISSUE TITLE
Minted v3 errors when using \includeonly

### ISSUE THREAD

**Issue by plescornet** [gpoore/minted#414]
Hi !
With the minted v3 release, I noticed that it breaks my documents when I use `\includeonly`.
minted version : 3.1.2
Everything else related is up to date.

Here is a MWE :

```latex
% mwe.tex
\documentclass{article}

\usepackage{minted}

% \includeonly{mwe2.tex}

\begin{document}
\include{mwe1.tex}
\include{mwe2.tex}
\end{document}
```

```latex
% mwe1.tex
\begin{minted}{ocaml}
  let ex_1 = 0
\end{minted}
```

```latex
% mwe1.tex
\begin{minted}{ocaml}
  let ex_2 = 0
\end{minted}
```

My compilation process is :
```shell
$ latexmk mwe
# Everything works

# uncomment the includeonly command
$ latexmk mwe
[...]
(./mwe.aux (./mwe1.aux) (./mwe2.aux))

! LaTeX Error: No counter 'minted@tmpdatabufferlength' defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.8 \include{mwe1.tex}

?
```

This was not a problem in minted v2.*, this compilation process works when using `minted2` instead of `minted` (with `--shell-escape`).

Is this an expected regression with the new version ? Thanks for your help.

**Comment by gpoore** [comment]
`\includeonly` changes the way that counters behave, so fixing this also involved modifying `latex2pydata` and `fvextra`. You can download the dev version of [`minted.sty`](https://github.com/gpoore/minted/blob/d4c8a703a191f44626a0c4d85750030e55bed98b/latex/minted/minted.sty) as well as the dev versions of [`latex2pydata.sty`](https://github.com/gpoore/latex2pydata/blob/main/latex/latex2pydata/latex2pydata.sty) and [`fvextra`](https://github.com/gpoore/fvextra/blob/master/fvextra/fvextra.sty) to try the new version immediately. Otherwise, new releases of all packages will be on CTAN within the next few days.

**Comment by plescornet** [comment]
The last release on CTAN fixed it, sorry I did not test it sooner. Closing now. Thanks for this amazing tool !
