### ISSUE TITLE
minted does not play nicely with latexrun

### ISSUE THREAD

**Issue by matze** [gpoore/minted#55]
latexrun is a LaTeX driver that is able to output auxiliary files in a separate build dir. Unfortunately, minted somehow [gets stuck](https://github.com/aclements/latexrun/issues/13) when `input`ing the intermediate pygmentized output.

**Comment by gpoore** [comment]
I've done a lot of additional investigating, and since there is still no general way to reconcile `-output-directory` and `\write18`, I am closing this.

When `-output-directory` is in use, it leaves no trace that is detectable by `kpsewhich` or similar means. In the next release, I have added error messages that alert users to the `-output-directory` issues, and the existence of the `outputdir` package option, whenever `\input`ing `minted` files fails.

For future reference, the test document below typesets a lot of the standard paths where one might hope that `-output-directory` would leave a trace. Sadly, it doesn't. This document must be compiled with `-shell-escape`, and requires Python.
```latex
\documentclass{article}
\begin{document}
\newwrite\testfile
\immediate\openout\testfile test.pyg
\immediate\write\testfile{test}
\immediate\closeout\testfile
Where is the file ``test.pyg''? \input{|"kpsewhich 'test.pyg' || echo 'NO RESULT'"}
~\par
Current paths from \verb|kpsewhich|: 
\begingroup
\catcode`\:=\active
\let:\par
\ttfamily
\input{|"kpsewhich --show-path tex"}
\endgroup
~\par
Current value of \verb|\input@path|:
\begingroup
\makeatletter
\ttfamily
\ifcsname input@path\endcsname\input@path\else <NONE>\fi
\makeatother
\endgroup
~\par
TEXINPUTS: 
\begingroup
\catcode`\,=\active
\let,\par
\ttfamily
\input{|"kpsewhich -var-value TEXINPUTS"}
\endgroup
~\par
Python current working directory:  \input{|"python -c 'import os; print(os.getcwd());'"}
(Python will complain, but this works.)
\end{document}
```
