### ISSUE TITLE
comma in comment with mathescape results in infinite loop when using icomma

### ISSUE THREAD

**Issue by svrnwnsch** [gpoore/minted#59]
What steps will reproduce the problem?
1. use \inputminted[mathescape]{python}{test.py}
2. test.py contains "# $(a_n,b)$" or something else with "$,$"
3. try to compile with LaTeX results in Error: "! TeX capacity exceeded, sorry [main memory size=5000000]."
4. try to compile with LuaLaTeX consumes all memory but never finishes

What is the expected output? What do you see instead?
Korrekt LaTeX with normal comma in mathmode.

What version of the product are you using? On what operating system?
Texmaker 4.3, Pygments-2.0.1-py2.7.egg, pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014/Debian)
-----
This is a copy of my request on google code https://code.google.com/p/minted/issues/detail?id=90

**Comment by gpoore** [comment]
This is due to the way that ligatures are dealt with in verbatim content. It may be fixed by adding this to your preamble after loading `icomma` and `minted`.
```
\begingroup
\catcode`\,=\active
\global\let\icomma@minted,
\endgroup
\apptocmd{\@noligs}{%
  \begingroup
  \lccode`\~=`\,
  \lowercase{\endgroup\def~}{%
    \ifmmode
      \expandafter\icomma@minted
    \else
      \leavevmode\kern\z@\char`\,
    \fi}}%
  {}{}
\makeatother
```
More information about how all of this works is available [here](http://tex.stackexchange.com/questions/223876/fancyvrb-error-with-math-escapes-and-prime).

I have added a note to the next version of the documentation about how to deal with these sorts of cases. For now, I am not going to attempt to build a patching mechanism into `minted` itself, because `\@noligs` is in the LaTeX core. Modifying `\@noligs` within a single document is fine, but any attempt to modify it in a package is asking for package conflicts. I will consider adding a patching mechanism in the future if I can figure out a sensible interface with minimal potential for conflicts.
