### ISSUE TITLE
post-processed .tex file?

### ISSUE THREAD

**Issue by soonhokong** [gpoore/minted#63]
Is there any way to get a post-processed .tex file, so that we can send it to an editor who doesn't have a pygments installed?

**Comment by gpoore** [comment]
There isn't currently a way to do this automatically. In principle, it would be possible to do it. However, it would mean that instead of having source code in your document, which is readable, you would have source code mixed with Pygments markup and style definitions. This would make the code unreadable in the .tex file. I would recommend using `verbatim` or perhaps the `Verbatim` defined by `fancyvrb` instead. You lose the highlighting, but the .tex file remains readable.

If you really do want this, you could take the .tex file and combine it with the cached highlighted output (assuming you are using minted 2.0, which caches by default). You would need to replace the `\usepackage{minted}` with `\usepackage{fancyvrb, xcolor}`. You would also need to put the Pygments style definitions in the preamble. Then you could replace each bit of highlighted code with its corresponding Pygments output. Even then, you would lose any `fancyvrb` options unless you translated those over as well. For a very simple document, this wouldn't be too hard to do manually. For a more complex document, it could be very difficult even to write a post-processor to do it automatically, since the post-processor might have to understand LaTeX to find the replacement locations properly.

**Comment by soonhokong** [comment]
@gpoore, thanks for the quick reply!

As you may expect, I'm thinking about a scenario where I send a camera-ready LaTeX source (not PDF) to editors. For this, definitely the readability of source file is not an issue. Normally, they expect the source code can be compiled via a couple of pdflatex/bibtex combinations.

It seems that all I can do for now is to prepare a `Makefile` which automates the process of building `pygments` and let `minted` use it. Hopefully, editors will accept this.

Again, thanks for the answer!!
