### ISSUE TITLE
Minted fails when documentclass is `standalone`

### ISSUE THREAD

**Issue by goodmami** [gpoore/minted#68]
Minted generates erroneous tex code when the document class is standalone. Consider this:

```tex
\documentclass{standalone}

\usepackage{minted}
\usemintedstyle{trac}

\begin{document}
\begin{minted}{xml}
<root>
</root>
\end{minted}
\end{document}
```

When I try to compile, I get this error message:

```
! LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.1 \begin{Verbatim}[commandchars=\\\{\}, ]
                                           
? 
! Emergency stop.
 ...                                              
                                                  
l.1 \begin{Verbatim}[commandchars=\\\{\}, ]
```

Notice how there is a comma in the options but nothing after it. Changing the documentclass to something else (like `article`) allows the document to be typeset without error.

**Comment by gpoore** [comment]
This is due to `standalone`. *Any* verbatim content would fail in this situation.

You need to use `standalone` with the `varwidth` or `preview` options to get this to compile without errors, and then you may have to make some adjustments to get margins the way you want. See https://bitbucket.org/martin_scharrer/standalone/issue/5/possible-imcompatibility-with-verbatimsty.

**Comment by goodmami** [comment]
Ah I see. Thank you for the very quick response. I wasn't aware of this limitation of standalone, and the error message from latex was (as usual) cryptic and misleading.

The `varwidth` solution seems to work well enough.
