### ISSUE TITLE
MakeFile lexer : Some word are no colored

### ISSUE THREAD

**Issue by TApplencourt** [gpoore/minted#84]
Hi, 

The syntax coloration for the MakeFile lexer seem to have a bug. I use the monokai style for this exemple.

MWE (i use the last minted.sty i guess)

```latex
\documentclass{article}

\usepackage{minted}
\usemintedstyle{monokai,bgcolor=black}

\begin{document}

\begin{minted}{Makefile}
var    = value

target: children
#Commentary
    command
\end{minted}

\end{document}
```

Produce

![selection_012](https://cloud.githubusercontent.com/assets/6524907/9386030/f0d51f92-4759-11e5-8b68-2bc24ffbca73.png)

and as you can see (ohohoh) `value` is invisible, is still in black.

If you use directly pygmentize (the last version 2.0.2)
```pygmentize -l Makefile -O full,style=monokai <file>```
it will produce the correct coloration

![selection_013](https://cloud.githubusercontent.com/assets/6524907/9386078/2c4d3adc-475a-11e5-923b-df6c08bd3137.png)

I hope this may help you,
Thomas

**Comment by gpoore** [comment]
There are several things going on here.

First, the document output and the console output won't necessarily match exactly...that could be interpreted as a bug in [Pygments](https://bitbucket.org/birkenfeld/pygments-main/), but it's possible there's a reason related to how consoles do colors. My console output is similar to yours, but the colors are different shades.

Second, Pygments doesn't specify a color for default text. Again, this might be interpreted as a bug. Since the **document's** default text color is black, and Pygments doesn't specify a color, then default text is black, which is bad on a black background. The solution is to manually specify a default color. For example, you could add `\AtBeginEnvironment{minted}{\color{white}}` to your preamble, and then within `minted` environments all default text will be white. ([Related issue](https://github.com/gpoore/minted/issues/72).)

As a side note, `\setminted{style=monokai, bgcolor=black}` would be better than `\usemintedstyle{monokai,bgcolor=black}`. The fact that `\usemintedstyle` works at all with a non-style option is actually a bug in the argument parsing.

**Comment by TApplencourt** [comment]
First, please excuse me if my first message seem rude.
And second, thx for the fix/work-around!

**Comment by TApplencourt** [comment]
Hi,

the `\AtBeginEnvironment{minted}{\color{white}}` trick work but not  in`\mintinline` environement. 

MWE

```latex
\documentclass{article}

\usepackage{minted}

\setminted{style=monokai, bgcolor=black}
\AtBeginEnvironment{minted}{\color{white}}

\begin{document}

\begin{minted}{bash}
$ git --init
\end{minted}

Inline : \mintinline{bash}{$ git --init}

\end{document}
```

**Comment by gpoore** [comment]
Unfortunately, you have to patch each command/environment separately. And doing the commands can be more difficult. Here's a fix for `\mintinline` that you can add to the preamble. I will look into adding an option for setting the default text color, so that this is simpler.

```latex
\makeatletter
\renewrobustcmd{\mintinline}[2][]{%
  \begingroup
  \color{white}%  <<---- Fix color
  \setboolean{minted@isinline}{true}%
  \minted@configlang{#2}%
  \setkeys{minted@opt@cmd}{#1}%
  \minted@fvset
  \begingroup
  \let\do\@makeother\dospecials
  \catcode`\{=1
  \catcode`\}=2
  \catcode`\^^I=\active
  \@ifnextchar\bgroup
    {\minted@inline@iii}%
    {\catcode`\{=12\catcode`\}=12
      \minted@inline@i}}
\makeatother
```

**Comment by TApplencourt** [comment]
This work !  
 Yes, maybe a  `defaultcolor` option will be useful for somebody else to.

 Thanks for all !
