### ISSUE TITLE
Weird folder gets created when tilde is used in outputdir path

### ISSUE THREAD

**Issue by fubuloubu** [gpoore/minted#89]
I had my output directory for pdftex set to a directory in my home directory, so I decided naively to use `outputdir="~/Downloads"` in my options for minted. I realize now that it doesn't like the tilde operator for paths, but the weird thing is that it creates a random '{}/' directory in my build folder. I'm going to assume the rest are just folders minted/pygments is making.

My command:
`~/git-work/project/$ pdflatex -shell-escape -output-directory ~/Downloads project.tex`:
Here's a ls afterwards:
`~/git-work/project/$ ls`
 `{}/  @M/  project.tex  Makefile  penalty/  protect/  unhbox/  voidb@x/`

When I use an absolute path, it works fine and none of these intermediate folders are there.

Based on the build output for pdftex, I think it translated the tilde operator into '{}' for some reason
`This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013/Debian)`
`...`
`rm: cannot remove 'protect': Is a directory`
`rm: cannot remove 'unhbox': Is a directory`
`rm: cannot remove 'voidb@x': Is a directory`
`rm: cannot remove 'penalty': Is a directory`
`rm: cannot remove '@M': Is a directory`
`rm: cannot remove ' {}/Downloads/_minted-HW3/8AAECF39E00872F5EB1C179AD2FC10774F9E9ECE296B25EA9D725AED989B049F.pygtex': No such file or directory`
`rm: cannot remove 'protect': Is a directory`
`rm: cannot remove 'unhbox': Is a directory`
`rm: cannot remove 'voidb@x': Is a directory`
`rm: cannot remove 'penalty': Is a directory`
`rm: cannot remove '@M': Is a directory`
`rm: cannot remove ' {}/Downloads//HW3.pyg': No such file or directory`
`rm: cannot remove 'protect': Is a directory`
`rm: cannot remove 'unhbox': Is a directory`
`rm: cannot remove 'voidb@x': Is a directory`
`rm: cannot remove 'penalty': Is a directory`
`rm: cannot remove '@M': Is a directory`
`rm: cannot remove ' {}/Downloads//HW3.out.pyg': No such file or directory`
`...`
`Transcript written on /home/baconbit/Downloads/project.log.`
`make: *** [project.pdf] Error 1`
`shell returned 2`

I know this might be undefined behavior, but a warning or error would've been nicer than creating this random '{}/' directory. I couldn't even figure out how to rm it, so I had to move everything and torch the upper level directory instead, which was annoying.

**Comment by gpoore** [comment]
The tilde is being treated as the non-breaking space (the usual LaTeX meaning), rather than as a literal tilde character to be passed to the operating system. I got a mostly complete patch working yesterday, but it will probably be a couple more days before I can finish testing the patch and put up a new version. Fixing this properly will involve multiple changes throughout the package.

**Comment by gpoore** [comment]
Sorry about the long delay on this.

Using something like `outputdir=\string~/Downloads` or `outputdir=\detokenize{~/Downloads}` should work now. Basically, any special characters must be escaped so that they are treated literally (`~` in this case). Quoting is only needed around parts of paths containing spaces, and in that case the entire argument to `outputdir` (or `cachedir`) must be wrapped in curly braces `{...}`.

I've added notes about all of this and examples in the docs.
