### ISSUE TITLE
dblatex generated output does not play nice with minted

### ISSUE THREAD

**Issue by shivshankardayal** [gpoore/minted#91]
First of all it may not be an issue with minted because my normal latex files are working but I have a large latex file generated with dblatex. When I replace lstlisting environment with minted it fails to process it. xelatex produces following errror:

! Missing \endcsname inserted.
<to be read again> 
               \global 
l.2 ...de \PYGdefaultZlt{}stdio.h\PYGdefaultZgt{}}

Has anyone tried using dblatex with minted? https://github.com/sciactive/2be-extras/blob/master/documentation/doc-pdf.sh git repository has integration of dblatex with minted but even that does not work.
˘
A sample xml can be

<article xmlns="http://docbook.org/ns/docbook" 
          xmlns:xl="http://www.w3.org/1999/xlink" version="5.0">
      <title>Test article</title>

     <para>
     <application xl:href="http://www.gnu.org/software/emacs/">Emacs</application> 
        is my favourite text editor.</para>
     ...
    <programlisting language="c">#include &lt;stdio.h&gt;</programlisting>
    </article>

The tex file can be generated via command dblatex -bxetex -p dblatex.xsl -t tex test.xml.

Then minted can be included and processed with xelatex for the error.

**Comment by gpoore** [comment]
If you can create a very short document that creates the error, and post the complete LaTeX source that dblatex outputs, I can take a look at that and possibly track down the error. I don't have dblatex installed, so I can't test it directly.

**Comment by shivshankardayal** [comment]
I am giving small generated document.
```latex
% -----------------------------------------  
% Autogenerated LaTeX file from XML DocBook  
% -----------------------------------------  
%%<params>
%%</params>
\documentclass[a4paper,10pt,twoside,openright]{article}
\IfFileExists{ifxetex.sty}{%
    \usepackage{ifxetex}%
  }{%
    \newif\ifxetex
    \xetexfalse
  }
  \ifxetex
\usepackage{fontspec}
\usepackage{xltxtra}
\defaultfontfeatures{Mapping=tex-text}
\setmainfont[Ligatures=TeX,Scale=1]{Times}
    \setsansfont[Ligatures=TeX,Scale=.95]{Helvetica}
    \setmonofont{Courier}
    \else
\usepackage[T1]{fontenc}
\usepackage[latin1]{inputenc}
\fi
\usepackage{fancybox}
\usepackage{makeidx}
\def\hyperparam{colorlinks,linkcolor=cyan,anchorcolor=cyan,urlcolor=cyan}
\usepackage[includeheadfoot,papername=a4paper,top=.5in,bottom=.5in,twoside]{geometry}
\usepackage[hyperlink]{db2latex}
\renewcommand{\DBKreleaseinfo}{}
\renewcommand{\DBKrevhistory}{}
\setcounter{tocdepth}{5}
\setcounter{secnumdepth}{5}
\title{Test article}
\author{}
\hypersetup{%
pdfcreator={DBLaTeX-0.3.5},%
pdftitle={Test article},%
pdfauthor={}%
}
\renewcommand{\DBKindexation}{}
\makeindex
\makeglossary
\usepackage{verbments}
\begin{document}
\lstsetup
\frontmatter
\maketitle
\tableofcontents
\mainmatter

  Emacs         is my favourite text editor.

\begin{minted}{c}
#include <stdio.h>
\end{minted}

\end{document}
```

**Comment by shivshankardayal** [comment]
Please replace verbments with minted. I was trying that as well.

**Comment by gpoore** [comment]
There are a lot of things that have to be fixed.

`fancybox` and `fancyvrb` conflict. For things to work correctly, `fancyvrb` must be loaded last. Both of these packages are already loaded by `db2latex`, so neither of them are needed in your output `.tex` file.  

The package `db2latex` attempts to load the two packages in the correct order, but overlooks the fact that it has already loaded `fancyvrb` in the subpackage `dbk_verbatim`, which loads `listings` which loads `fancyvrb`. Even if that wasn't the case, `dbk_misc` would load `fancyvrb` explicitly. So `db2latex` ultimately ends up loading `fancybox` last, which is wrong. You would need to comment out the `\usepackage{fancybox}` in `db2latex.sty`, or move it to before `\usepackage{dbk_verbatim}`.

If `fancybox` is loaded anywhere by `db2latex`, then `minted` must be loaded *after* `db2latex`, because `minted` will load `fancyvrb`, and thus `fancyvrb` wouldn't be loaded last. If `fancybox` isn't ever loaded, then `minted` can be loaded anywhere.

Once that is done, there is still a problem because `dbk_misc.sty` uses `\lstset{fancyvrb=true}`, which overwrites the `fancyvrb` internals with `listings` versions. You would need to comment that out, or have `\lstset{fancyvrb=false}` in your output document somewhere *after* loading `db2latex`.

**Comment by shivshankardayal** [comment]
Thanks a bunch. I was loading minted last but I do not know TeX much. I barely survive. I just put one line `\lstset{fancyvrb=false}` and that did the trick. There is the same question on stackexchange where youcan answer for other. http://tex.stackexchange.com/questions/273995/dblatex-generated-output-does-not-play-nice-with-minted

**Comment by shivshankardayal** [comment]
I really appreciate your help even though it was not a minted issue.
