### ISSUE TITLE
minted in Pandoc

### ISSUE THREAD

**Issue by AndiH** [gpoore/minted#93]
I'm looking into using [Pandoc](https://github.com/jgm/pandoc) for generating my LaTeX beamer slides. Surely, they will include code snippets, which I like to set with minted (because the result just looks amazing).

I spent the morning tracing back why Pandoc wouldn't compile a document which looked perfectly fine to me. I'm quite certain that the reason lies in the `outputdir` option.

When Pandoc invokes pdflatex it does so by the following command: 
```
[makePDF] Command line:
pdflatex "-halt-on-error" "-interaction" "nonstopmode" "-output-directory" "/var/folders/9f/9ffrwq1x1k9fkbsvvnltq5kh0000gq/T/tex2pdf.88113" "-shell-escape" "/var/folders/9f/9ffrwq1x1k9fkbsvvnltq5kh0000gq/T/tex2pdf.88113/input.tex"
```
(at least that's what `pandoc --verbose` prints out as one of the first lines). Here, the `-output-directory` option is set to `pdflatex`. If I read the changes from the beginning of the year correctly, the value of this directory should be matched to the one given `minted` in the `outputdir` option. Manually, that seems impossible, since the temporary directory is chosen randomly. I can override the `-output-directory` when invoking Pandoc (`pandoc […] --latex-engine-opt -output-directory="."`) but then Pandoc will not work properly (also, it seems to rename files to `input.tex`).

Do you have any ideas how to teach minted the randomized output directory? Or how to take care of that problem?

I see that this is a issue not solely regarding minted (if at all!) but more the interplay between minted and Pandoc. I can also submit an issue over at Pandoc, but I thought reporting here first.

**Comment by gpoore** [comment]
This is probably impossible to solve on the `minted` side. As far as I know, there is no way to access the value of `-output-directory` from within LaTeX. Hence, the `outputdir` package option, which requires setting the output directory manually. What we really need is for LaTeX to set a macro `\joboutputdirectory`, just like it does for `\jobname`. But that doesn't currently exist.

I'm not sure what the best solution would be on the Pandoc side, since there may be restrictions that I'm not aware of.  My guess is that the best solution would be to create a temporary directory, `cd` to that directory, compile the LaTeX file there, and then move the output PDF to the desired location.

**Comment by klmr** [comment]
The easiest way is probably to use pandoc to generate the tex file only, and to invoke `pdflatex` manually afterwards. In fact, except for convenience there’s no real reason to let pandoc generate the PDF output.

**Comment by AndiH** [comment]
You are right, @klmr, I think this is the easiest solution. I lose a bit in convenience but gain in possibilities (e.g. to use `latexmk`). Thanks for the input!

**Comment by Evidlo** [comment]
You can find such a filter [here](https://gist.github.com/jepio/3ecaa6bba2a53ff74f2e).
