### ISSUE TITLE
C++ string not being highlighted

### ISSUE THREAD

**Issue by DurhamSmith** [gpoore/minted#94]
Hi,

Ive notice there seems to be a problem with highlighting string in c++ however other types seem fine. The error can be reproduced using

\mintinline{cpp}{int works = 'h';}\\
\mintinline{cpp}{string broken = "sad";}

\begin{minted}{cpp}
int main() {
printf("hello, world");
string d ="d";
int d =5;
return 0;
}
\end{minted}

**Comment by gpoore** [comment]
This is due to Pygments, which `minted` uses internally for doing the highlighting. The [Pygments C++ lexer](https://bitbucket.org/birkenfeld/pygments-main/src/f114940f5aeb4775eef157e7089f462b49bdc127/pygments/lexers/c_cpp.py?at=default&fileviewer=file-view-default) doesn't contain `string` in its list of keywords like `int`, etc. You could open an issue at the [Pygments BitBucket page](https://bitbucket.org/birkenfeld/pygments-main/issues?status=new&status=open), or customize your local copy of the lexer.

**Comment by klmr** [comment]
To clarify, Pygments (and minted) do everything correctly: `int` in C++ is a reserved keyword, and highlighted as such; `string`, on the other hand, *isn’t* a reserved word, it’s a normal identifier and is thus highlighted as a normal identifier.

If you want *all* type names to be highlighted, you need to write your own C++ parser; however, this will become very complex because it’s not enough to parse the code syntactically, you actually need to typecheck it. For inspiration you could take a look at [clighter](https://github.com/bbchung/clighter), which uses the libclang C++ parser library to implement this.

**Comment by gpoore** [comment]
@klmr Thanks for the clarification. I have almost no experience working with strings in C++.
