### ISSUE TITLE
Possibility to change showtabs character

### ISSUE THREAD

**Issue by AntoniniP** [gpoore/minted#98]
I would like to **show tabs with a custom character**, other than the default one which appears after `showtabs=true` option. As a reference, it would be perfect if I could use `\rightarrowfill`, just like I can do in `listings` package with the `tab=\rightarrowfill` option.

**Comment by gpoore** [comment]
The tab character is created by the [`fancyvrb` package](https://www.ctan.org/pkg/fancyvrb), which `minted` uses internally. The actual character is created by the command `\FancyVerbTab`. You can redefine that, using the original `fancyvrb` command as a starting point. Given the `fancyvrb` approach to tabs, using `\rightarrowfill` may be tricky, since both `fancyvrb` and the `\rightarrowfill` character will be trying to fill the available space.

`fancyvrb`'s treatment of tabs can be fragile (#99). Given the issues with tabs, I'm currently not willing to add a new option for working with the tab character, since it might break with future revisions of tab treatment. I'm adding a note to #99 that if it is fixed, then a setting for custom tab characters should also be added. For now, customizing `\FancyVerbTab` is an option.

**Comment by gpoore** [comment]
I'm closing this, since it depends on #99 and will be fixed when #99 is resolved. So in that sense it is a duplicate.

**Comment by gpoore** [comment]
In [v2.3](https://github.com/gpoore/minted/releases/tag/v2.3), there is a new `tab` option. Due to a reimplementation of tabbing, `\rightarrowfill` will now work. There is also a new `tabcolor` option.
